[project]
name = "litgpt"
version = "0.4.2"
description = "Hackable implementation of state-of-the-art open-source LLMs"
authors = [
    { name = "Lightning AI", email = "contact@lightning.ai" },
]
readme = "README.md"
license = { file = "LICENSE" }

dependencies = [
    "torch>=2.2.0",
    "lightning==2.3.0.dev20240428",
    "jsonargparse[signatures]>=4.27.6"
]

[project.urls]
homepage = "https://github.com/lightning-AI/litgpt"
documentation = "https://github.com/lightning-AI/litgpt/tutorials"

[project.scripts]
litgpt = "litgpt.__main__:main"

[project.optional-dependencies]
test = [
    "pytest>=8.1.1",
    "pytest-rerunfailures>=14.0",
    "pytest-timeout>=2.3.1",
    "pytest-dependency>=0.6.0",
    "transformers>=4.38.0",  # numerical comparisons
    "einops>=0.7.0",
    "protobuf>=4.23.4",
    "lightning-thunder==0.2.0.dev20240623; python_version >= '3.10'",
]
all = [
    "bitsandbytes==0.42.0",      # quantization
    "sentencepiece>=0.2.0",      # llama-based models
    "tokenizers>=0.15.2",        # pythia, falcon, redpajama
    "requests>=2.31.0",          # litgpt.data
    "litdata==0.2.6",            # litgpt.data
    "litserve>=0.1.2",           # litgpt.deploy
    "zstandard>=0.22.0",         # litgpt.data.prepare_slimpajama.py
    "numpy<2.0.0",               # PyTorch dependency; "pinned" until NumPy 2.0 is tested
    "pandas>=1.9.0",             # litgpt.data.prepare_starcoder.py
    "pyarrow>=15.0.2",           # litgpt.data.prepare_starcoder.py
    "tensorboard>=2.14.0",       # litgpt.pretrain
    "torchmetrics>=1.3.1",       # litgpt.pretrain
    "datasets>=2.18.0",          # litgpt.evaluate
    "transformers>=4.38.0",      # litgpt.evaluate
    "lm-eval>=0.4.2",            # litgpt.evaluate
    "safetensors>=0.4.3",        # download
    "huggingface_hub[hf_transfer]>=0.21.0"  # download
]

[build-system]
requires = [
    "setuptools>=68.2.2",
    "wheel>=0.41.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "litgpt",
    "litgpt.*",
]
exclude = []

[tool.setuptools.package-data]
litgpt = [
    "LICENSE",
    "README.md",
]
